version: "3.3"
services:
  cloudNet:
    image: chrros95/cloudNet:latest
    container_name: cloudNet
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    expose:
      - "655"
    network_mode: "host"
    volumes:
      - /var/service/cloudNet/volume:/etc/tinc