version: "3.2"
services:
  cloudNet:
    image: chrros95/cloudNet:latest
    container_name: cloudNet
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    expose:
      - "655"
    network_mode: "host"
    volumes:
      - ./volumes/tinc/:/etc/tinc